import { NextRequest, NextResponse } from 'next/server';
import { requireRole, getAccountScope, canAccessAccount } from '@/lib/api-auth';
import {
  createCampaignEmailTemplate,
  getCampaignRow,
  getCampaignWithAssets,
  linkAssetToCampaign,
  setCampaignStatus,
} from '@/lib/services/campaigns';
import {
  createDraftEmailBlast,
  updateEmailBlastDraft,
} from '@/lib/services/email-blasts';
import {
  createDraftSmsBlast,
  updateSmsBlastDraft,
} from '@/lib/services/sms-blasts';
import { generateEmailForSpec, finalizeSmsMessage } from '@/lib/ai/campaign-generators';
import { buildFormTemplate } from '@/lib/ai/form-builder';
import { generateLandingPageForSpec } from '@/lib/ai/lp-generator';
import { renderTemplateBuild } from '@/lib/email/build-to-html';
import { createForm } from '@/lib/services/forms';
import { createLandingPage } from '@/lib/services/landing-pages';
import type { CampaignBuildEvent } from '@/lib/campaigns/types';

// Uses Prisma + the Anthropic SDK + react-email's renderer — must be Node, and
// the SSE stream must never be cached. Allow plenty of time: emails are
// generated by Claude (concurrently, but still seconds each).
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 300;

interface RouteParams {
  params: Promise<{ id: string }>;
}

const EMAIL_CONCURRENCY = 3;

/** Bounded-concurrency runner. Workers handle their own errors and never throw. */
async function runPool<T>(items: T[], limit: number, worker: (item: T) => Promise<void>): Promise<void> {
  let cursor = 0;
  const runners = Array.from({ length: Math.min(Math.max(limit, 1), items.length) }, async () => {
    while (cursor < items.length) {
      const item = items[cursor++];
      await worker(item);
    }
  });
  await Promise.all(runners);
}

/**
 * POST /api/campaigns/[id]/generate
 *
 * Deterministic orchestrator: iterate the confirmed plan, generate each asset's
 * content, and persist a DRAFT via the existing draft services (NEVER the
 * schedule* path — nothing is ever sent here). Streams per-asset progress as
 * Server-Sent Events so the client can render a live "watch it build" UX.
 */
export async function POST(_req: NextRequest, { params }: RouteParams) {
  const { session, error } = await requireRole('developer', 'super_admin', 'admin');
  if (error) return error;

  const { id } = await params;
  const campaign = await getCampaignWithAssets(id);
  if (!campaign) return NextResponse.json({ error: 'Campaign not found' }, { status: 404 });

  const scope = getAccountScope(session!);
  if (campaign.accountKey && !canAccessAccount(scope, campaign.accountKey)) {
    return NextResponse.json({ error: 'Campaign not found' }, { status: 404 });
  }
  if (!campaign.accountKey) {
    return NextResponse.json({ error: 'Campaign has no account' }, { status: 400 });
  }
  if (!campaign.plan) {
    return NextResponse.json({ error: 'Campaign has no plan to generate' }, { status: 400 });
  }
  if (campaign.status === 'building') {
    return NextResponse.json({ error: 'Generation already in progress' }, { status: 409 });
  }
  if (campaign.assetCounts.total > 0) {
    return NextResponse.json({ error: 'Campaign already generated' }, { status: 409 });
  }

  const accountKey = campaign.accountKey;
  const plan = campaign.plan;

  const encoder = new TextEncoder();
  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      let closed = false;
      const send = (event: CampaignBuildEvent) => {
        if (closed) return;
        controller.enqueue(encoder.encode(`data: ${JSON.stringify(event)}\n\n`));
      };

      let successCount = 0;
      let errorCount = 0;

      try {
        await setCampaignStatus(id, 'building');

        // Pull the branding snapshot captured at plan time for grounded copy.
        const row = await getCampaignRow(id);
        const ctx = row?.contextSnapshot ?? undefined;

        const total =
          plan.emails.length + plan.sms.length + plan.forms.length + plan.landingPages.length;
        send({ type: 'plan_started', total });

        // ── Emails (concurrent, AI-generated) ──
        // Campaign-level format: 'blocks' → drag-and-drop visual, else Rich HTML.
        const emailMode: 'visual' | 'code' = plan.emailFormat === 'blocks' ? 'visual' : 'code';
        await runPool(plan.emails, EMAIL_CONCURRENCY, async (spec) => {
          send({ type: 'asset_started', kind: 'email', key: spec.key, label: spec.purpose });
          try {
            const { templateBuild, clarification } = await generateEmailForSpec(spec, {
              accountContext: ctx,
              campaignSummary: plan.summary,
              mode: emailMode,
              assets: plan.assets,
            });
            if (!templateBuild) {
              throw new Error(clarification || 'The email generator returned no content');
            }
            const rendered = await renderTemplateBuild(templateBuild, {
              subject: spec.subject,
              previewText: spec.previewText,
            });
            // Persist a real Template so the email previews + opens in the
            // editor natively. Visual → v2 JSON (editable); code → HTML.
            const templateSlug = await createCampaignEmailTemplate({
              accountKey,
              title: spec.subject || spec.purpose,
              previewText: spec.previewText,
              content: rendered.template ? JSON.stringify(rendered.template) : rendered.html,
              createdByUserId: session!.user.id,
            });
            const draft = await createDraftEmailBlast({
              name: spec.subject || spec.purpose,
              accountKeys: [accountKey],
              createdByUserId: session!.user.id,
              createdByRole: session!.user.role,
            });
            await updateEmailBlastDraft(draft.id, {
              subject: spec.subject,
              previewText: spec.previewText ?? null,
              htmlContent: rendered.html,
              textContent: rendered.textContent || null,
              sourceType: 'template-library',
              metadata: JSON.stringify({
                campaignSource: 'ai',
                campaignPlanKey: spec.key,
                templateSlug,
              }),
            });
            await linkAssetToCampaign('email', draft.id, id);
            successCount += 1;
            send({ type: 'asset_done', kind: 'email', key: spec.key, assetId: draft.id, name: spec.subject || spec.purpose });
          } catch (err) {
            errorCount += 1;
            send({
              type: 'asset_error',
              kind: 'email',
              key: spec.key,
              message: err instanceof Error ? err.message : 'Failed to generate email',
            });
          }
        });

        // ── SMS (no AI call — uses the confirmed plan message) ──
        for (const spec of plan.sms) {
          send({ type: 'asset_started', kind: 'sms', key: spec.key, label: spec.purpose });
          try {
            const message = finalizeSmsMessage(spec);
            if (!message) throw new Error('SMS message is empty');
            const draft = await createDraftSmsBlast({
              name: spec.purpose,
              accountKeys: [accountKey],
              createdByUserId: session!.user.id,
              createdByRole: session!.user.role,
            });
            await updateSmsBlastDraft(draft.id, {
              message,
              metadata: JSON.stringify({
                channel: 'SMS',
                mediaUrls: spec.mediaUrls ?? [],
                campaignSource: 'ai',
                campaignPlanKey: spec.key,
              }),
            });
            await linkAssetToCampaign('sms', draft.id, id);
            successCount += 1;
            send({ type: 'asset_done', kind: 'sms', key: spec.key, assetId: draft.id, name: spec.purpose });
          } catch (err) {
            errorCount += 1;
            send({
              type: 'asset_error',
              kind: 'sms',
              key: spec.key,
              message: err instanceof Error ? err.message : 'Failed to create SMS',
            });
          }
        }

        // ── Forms (deterministic) — created FIRST so a landing page can embed
        //    the real Form id. Both stay draft; the user publishes when ready. ──
        const formIdByKey: Record<string, string> = {};
        for (const spec of plan.forms) {
          send({ type: 'asset_started', kind: 'form', key: spec.key, label: spec.purpose });
          try {
            const { schema, name } = buildFormTemplate(spec, { accountContext: ctx });
            const form = await createForm({
              accountKey,
              name,
              schema,
              createdByUserId: session!.user.id,
            });
            formIdByKey[spec.key] = form.id;
            await linkAssetToCampaign('form', form.id, id);
            successCount += 1;
            send({ type: 'asset_done', kind: 'form', key: spec.key, assetId: form.id, name });
          } catch (err) {
            errorCount += 1;
            send({
              type: 'asset_error',
              kind: 'form',
              key: spec.key,
              message: err instanceof Error ? err.message : 'Failed to create form',
            });
          }
        }

        // ── Landing pages (AI HTML) — embed the just-created form by id. ──
        for (const spec of plan.landingPages) {
          send({ type: 'asset_started', kind: 'landingPage', key: spec.key, label: spec.purpose });
          try {
            const formId = spec.embeddedFormKey ? formIdByKey[spec.embeddedFormKey] : undefined;
            const { content, name } = await generateLandingPageForSpec(spec, {
              accountContext: ctx,
              campaignSummary: plan.summary,
              formId,
              assets: plan.assets,
            });
            const lp = await createLandingPage({
              accountKey,
              name,
              schema: content,
              createdByUserId: session!.user.id,
            });
            await linkAssetToCampaign('landingPage', lp.id, id);
            successCount += 1;
            send({ type: 'asset_done', kind: 'landingPage', key: spec.key, assetId: lp.id, name });
          } catch (err) {
            errorCount += 1;
            send({
              type: 'asset_error',
              kind: 'landingPage',
              key: spec.key,
              message: err instanceof Error ? err.message : 'Failed to create landing page',
            });
          }
        }

        // Clear 'building' so the derived status reflects the new assets.
        await setCampaignStatus(id, 'draft');
        const finalDetail = await getCampaignWithAssets(id);
        send({
          type: 'complete',
          campaignId: id,
          status: finalDetail?.status ?? (successCount > 0 ? 'ready' : 'draft'),
        });
      } catch (err) {
        // Catastrophic failure — try to leave the container in a sane state.
        try {
          await setCampaignStatus(id, 'draft');
        } catch {
          /* ignore */
        }
        send({
          type: 'error',
          message: err instanceof Error ? err.message : 'Generation failed',
        });
      } finally {
        closed = true;
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream; charset=utf-8',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive',
    },
  });
}
